#exp_condition: base
#exp_condition: random
exp_condition: reasonable

exp_welcome_message: "You are collaborating with a robot to decorate a square cake by drawing shapes on it.
\n
\nThe cake is represented as a 4 x 3 grid with columns labeled as a, b, c, d from left to right and rows labeled as 1, 2, 3 from bottom to top.
The robot can draw two shapes: hearts and houses. You may decorate the cake however you like. Here is an example of how you might communicate with the robot:
\n
\n\t- “draw a heart at location a3”
\n\t- “draw a house at location b2”
\n
\nThe robot can only take one action at a time. When you are done with the decoration, you may type \"done\" to end the conversation."
exp_chat_interface_title: "Robot"
user_name: Human
server_host: localhost
server_port: 8080
wait_for_action_completion: 5