task_setup:
  experiment_num: 0
  num_candles: 3
  surface_width: 5
  surface_height: 5
user_name: Helen
human_speech_record_len: 9 # record for this many seconds when it's the human user's turn to speak 
server_host: localhost
server_port: 8080
wait_for_action_completion: 3.7